"""create all 40 tables (M0)

Revision ID: b00c819f819c
Revises: 
Create Date: 2026-08-23 23:51:13.796447

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b00c819f819c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_hash', sa.Text(), nullable=True),
    sa.Column('after_hash', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('CREATE', 'UPDATE', 'APPROVE', 'REJECT', 'EXECUTE', 'REVERSE', 'SUPERSEDE', 'STATUS_CHANGE', 'LOGIN')", name=op.f('ck_audit_events_action_check')),
    sa.CheckConstraint("actor_type IN ('HERMES', 'HUMAN', 'SYSTEM', 'JOB')", name=op.f('ck_audit_events_actor_type_check')),
    sa.PrimaryKeyConstraint('audit_event_id', name=op.f('pk_audit_events'))    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('daily_contexts',
    sa.Column('daily_context_id', sa.UUID(), nullable=False),
    sa.Column('market_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('freshness_status', sa.Text(), nullable=False),
    sa.Column('data_freshness', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('markets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("freshness_status IN ('OK', 'WARNING', 'STALE', 'FAILED')", name=op.f('ck_daily_contexts_freshness_status_check')),
    sa.PrimaryKeyConstraint('daily_context_id', name=op.f('pk_daily_contexts')),
    sa.UniqueConstraint('market_date', name='uq_daily_contexts_market_date')    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('instrument_type', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='CNY', nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('isin', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("instrument_type IN ('CN_EQUITY', 'CN_ETF', 'INDEX')", name=op.f('ck_instruments_instrument_type_check')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'DELISTED')", name=op.f('ck_instruments_status_check')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('symbol', 'market', name='uq_instruments_symbol_market')    )
    op.create_table('job_runs',
    sa.Column('job_run_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_version', sa.Text(), nullable=True),
    sa.Column('output_version', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('SYNC_JOB', 'COMPUTE_JOB', 'INGESTION', 'BRIEF_JOB')", name=op.f('ck_job_runs_job_type_check')),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SUPERSEDED')", name=op.f('ck_job_runs_status_check')),
    sa.PrimaryKeyConstraint('job_run_id', name=op.f('pk_job_runs'))    )
    op.create_index('ix_job_runs_name_created', 'job_runs', ['job_name', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('outbox_events',
    sa.Column('outbox_event_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PUBLISHED', 'FAILED')", name=op.f('ck_outbox_events_status_check')),
    sa.CheckConstraint("topic IN ('AUDIT', 'PROVENANCE', 'NOTIFICATION')", name=op.f('ck_outbox_events_topic_check')),
    sa.PrimaryKeyConstraint('outbox_event_id', name=op.f('pk_outbox_events'))    )
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('base_currency', sa.Text(), server_default='CNY', nullable=False),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("base_currency = 'CNY'", name=op.f('ck_portfolios_base_currency_cny')),
    sa.CheckConstraint("mode IN ('REAL', 'PAPER')", name=op.f('ck_portfolios_mode_check')),
    sa.CheckConstraint("status IN ('ACTIVE', 'CLOSED')", name=op.f('ck_portfolios_status_check')),
    sa.PrimaryKeyConstraint('portfolio_id', name=op.f('pk_portfolios'))    )
    op.create_table('research_workspaces',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'ARCHIVED')", name=op.f('ck_research_workspaces_status_check')),
    sa.CheckConstraint("subject_type IN ('INSTRUMENT', 'THESIS', 'GENERAL')", name=op.f('ck_research_workspaces_subject_type_check')),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_research_workspaces'))    )
    op.create_table('theses',
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('lifecycle_status', sa.Text(), nullable=False),
    sa.Column('health_status', sa.Text(), nullable=False),
    sa.Column('conviction', sa.Text(), nullable=True),
    sa.Column('fair_value_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fair_value_base', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fair_value_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_revision_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("conviction IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_theses_conviction_check')),
    sa.CheckConstraint("health_status IN ('UNKNOWN', 'HEALTHY', 'WARNING', 'BROKEN')", name=op.f('ck_theses_health_status_check')),
    sa.CheckConstraint("lifecycle_status IN ('DRAFT', 'ACTIVE', 'UNDER_REVIEW', 'INVALIDATED', 'ARCHIVED')", name=op.f('ck_theses_lifecycle_status_check')),
    sa.PrimaryKeyConstraint('thesis_id', name=op.f('pk_theses'))    )
    op.create_table('thesis_revisions',
    sa.Column('thesis_revision_id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('thesis_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('authored_by', sa.Text(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thesis_revision_id', name=op.f('pk_thesis_revisions')),
    sa.UniqueConstraint('thesis_id', 'version', name='uq_thesis_revisions_thesis_version')    )
    op.create_index('ix_thesis_revisions_thesis', 'thesis_revisions', ['thesis_id', sa.literal_column('version DESC')], unique=False)
    op.create_table('trading_calendar',
    sa.Column('calendar_entry_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('session_status', sa.Text(), nullable=False),
    sa.Column('holiday_name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("market IN ('CN', 'US')", name=op.f('ck_trading_calendar_market_check')),
    sa.CheckConstraint("session_status IN ('OPEN', 'CLOSED', 'PARTIAL')", name=op.f('ck_trading_calendar_session_status_check')),
    sa.PrimaryKeyConstraint('calendar_entry_id', name=op.f('pk_trading_calendar')),
    sa.UniqueConstraint('market', 'trade_date', name='uq_trading_calendar_market_date')    )
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), server_default='CNY', nullable=False),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('CASH', 'BROKERAGE')", name=op.f('ck_accounts_account_type_check')),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_accounts'))    )
    op.create_table('attention_items',
    sa.Column('attention_item_id', sa.UUID(), nullable=False),
    sa.Column('daily_context_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('rule_name', sa.Text(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('attention_item_id', name=op.f('pk_attention_items'))    )
    op.create_table('daily_briefs',
    sa.Column('daily_brief_id', sa.UUID(), nullable=False),
    sa.Column('daily_context_id', sa.UUID(), nullable=False),
    sa.Column('market_date', sa.Date(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_profile', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'FAILED')", name=op.f('ck_daily_briefs_status_check')),
    sa.PrimaryKeyConstraint('daily_brief_id', name=op.f('pk_daily_briefs')),
    sa.UniqueConstraint('market_date', name='uq_daily_briefs_market_date')    )
    op.create_table('etf_profiles',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('is_qdii', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('underlying_index_id', sa.UUID(), nullable=True),
    sa.Column('fund_manager', sa.Text(), nullable=True),
    sa.Column('fund_name', sa.Text(), nullable=True),
    sa.Column('tracking_index_name', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('is_qdii = FALSE OR underlying_index_id IS NOT NULL', name=op.f('ck_etf_profiles_qdii_index')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_etf_profiles'))    )
    op.create_table('portfolio_snapshots',
    sa.Column('portfolio_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('as_of', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cash_cny', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('market_value_cny', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('nav_cny', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('exposures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_snapshot_id', name=op.f('pk_portfolio_snapshots')),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_snapshots_pf_date')    )
    op.create_table('position_snapshots',
    sa.Column('position_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('cost_basis_cny', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('market_price_cny', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_value_cny', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl_cny', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl_cny', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_qdii', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('position_snapshot_id', name=op.f('pk_position_snapshots')),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', 'snapshot_date', name='uq_position_snapshots_pf_inst_date')    )
    op.create_index('ix_position_snapshots_pf_date', 'position_snapshots', ['portfolio_id', sa.literal_column('snapshot_date DESC')], unique=False)
    op.create_table('provenance_records',
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('observed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=True),
    sa.Column('raw_object_key', sa.Text(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('transform_version', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quality_status IN ('VERIFIED', 'ACCEPTABLE', 'STALE', 'CONFLICT', 'REJECTED')", name=op.f('ck_provenance_records_quality_status_check')),
    sa.CheckConstraint("source_kind IN ('OFFICIAL_FILING', 'EXCHANGE', 'PROVIDER', 'HUMAN', 'HERMES', 'DERIVED_ENGINE')", name=op.f('ck_provenance_records_source_kind_check')),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 1', name=op.f('ck_provenance_records_quality_score_range')),
    sa.PrimaryKeyConstraint('provenance_id', name=op.f('pk_provenance_records'))    )
    op.create_index('ix_provenance_asof_quality', 'provenance_records', ['as_of_date', 'quality_status'], unique=False)
    op.create_index('ix_provenance_provider_record', 'provenance_records', ['provider', 'source_record_id'], unique=False)
    op.create_table('provider_symbols',
    sa.Column('provider_symbol_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider_symbol_id', name=op.f('pk_provider_symbols')),
    sa.UniqueConstraint('provider', 'symbol', 'valid_from', name='uq_provider_symbols_provider_sym_from')    )
    op.create_index('ix_provider_symbols_instrument', 'provider_symbols', ['instrument_id'], unique=False)
    op.create_index('ix_provider_symbols_lookup', 'provider_symbols', ['provider', 'symbol'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('research_threads',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('thread_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('THREAD_OPEN', 'PAUSED', 'CLOSED')", name=op.f('ck_research_threads_status_check')),
    sa.CheckConstraint("thread_type IN ('RESEARCH', 'ANALYSIS', 'REVIEW')", name=op.f('ck_research_threads_thread_type_check')),
    sa.PrimaryKeyConstraint('thread_id', name=op.f('pk_research_threads'))    )
    op.create_table('target_allocations',
    sa.Column('target_allocation_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('asset_class', sa.Text(), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('rebalance_frequency', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_weight >= 0 AND target_weight <= 1', name=op.f('ck_target_allocations_target_weight_range')),
    sa.PrimaryKeyConstraint('target_allocation_id', name=op.f('pk_target_allocations'))    )
    op.create_table('thesis_assumptions',
    sa.Column('assumption_id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('thesis_revision_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('test_condition', sa.Text(), nullable=True),
    sa.Column('verification_frequency', sa.Text(), nullable=True),
    sa.Column('is_red_line', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('superseded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('BUSINESS', 'FINANCIAL', 'VALUATION', 'MACRO', 'GOVERNANCE')", name=op.f('ck_thesis_assumptions_category_check')),
    sa.CheckConstraint("status IN ('UNKNOWN', 'HEALTHY', 'WARNING', 'BROKEN')", name=op.f('ck_thesis_assumptions_status_check')),
    sa.PrimaryKeyConstraint('assumption_id', name=op.f('pk_thesis_assumptions'))    )
    op.create_table('thesis_events',
    sa.Column('thesis_event_id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('CREATED', 'REVISION', 'REVIEW', 'RED_FLAG_TRIGGERED', 'DRIFT_DETECTED', 'STATUS_CHANGED', 'HEALTH_CHANGED')", name=op.f('ck_thesis_events_event_type_check')),
    sa.PrimaryKeyConstraint('thesis_event_id', name=op.f('pk_thesis_events'))    )
    op.create_index('ix_thesis_events_thesis', 'thesis_events', ['thesis_id', 'created_at'], unique=False)
    op.create_table('valuation_runs',
    sa.Column('valuation_run_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('as_of', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('input_snapshot_hash', sa.Text(), nullable=True),
    sa.Column('bear_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('base_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bull_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('margin_of_safety', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("model_type IN ('DCF', 'DDM', 'OWNER_EARNINGS', 'COMPARABLE', 'SCENARIO')", name=op.f('ck_valuation_runs_model_type_check')),
    sa.CheckConstraint("status IN ('CREATED', 'VALIDATING', 'BLOCKED_MISSING_INPUT', 'RUNNING', 'COMPLETED', 'FAILED', 'SUPERSEDED')", name=op.f('ck_valuation_runs_status_check')),
    sa.PrimaryKeyConstraint('valuation_run_id', name=op.f('pk_valuation_runs'))    )
    op.create_index('ix_valuation_runs_inst_asof', 'valuation_runs', ['instrument_id', sa.literal_column('as_of DESC')], unique=False)
    op.create_table('corporate_actions',
    sa.Column('corporate_action_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('announce_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adj_factor', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('DIVIDEND', 'SPLIT', 'BONUS_SHARE', 'RIGHTS_ISSUE')", name=op.f('ck_corporate_actions_action_type_check')),
    sa.CheckConstraint("status IN ('ANNOUNCED', 'IMPLEMENTED', 'ADJUSTED')", name=op.f('ck_corporate_actions_status_check')),
    sa.PrimaryKeyConstraint('corporate_action_id', name=op.f('pk_corporate_actions'))    )
    op.create_index('ix_corporate_actions_inst_exdate', 'corporate_actions', ['instrument_id', 'ex_date'], unique=False)
    op.create_table('etf_holding_snapshots',
    sa.Column('holding_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('report_period', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('holding_count', sa.Integer(), nullable=True),
    sa.Column('holdings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parquet_path', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('QUARTERLY', 'HALF_YEAR', 'ANNUAL', 'OTHER')", name=op.f('ck_etf_holding_snapshots_source_check')),
    sa.PrimaryKeyConstraint('holding_snapshot_id', name=op.f('pk_etf_holding_snapshots')),
    sa.UniqueConstraint('instrument_id', 'report_period', 'source', name='uq_etf_holdings_inst_period_source')    )
    op.create_table('etf_metric_snapshots',
    sa.Column('etf_metric_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('market_date', sa.Date(), nullable=False),
    sa.Column('is_qdii', sa.Boolean(), nullable=False),
    sa.Column('underlying_index_id', sa.UUID(), nullable=True),
    sa.Column('market_price_cny', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('nav_date', sa.Date(), nullable=True),
    sa.Column('underlying_session_date', sa.Date(), nullable=True),
    sa.Column('premium_discount', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fx_contribution', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fx_as_of', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('quota_status', sa.Text(), nullable=True),
    sa.Column('net_value_t1', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('index_pe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('index_pb', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quality_status IN ('VERIFIED', 'ACCEPTABLE', 'STALE', 'CONFLICT', 'REJECTED')", name=op.f('ck_etf_metric_snapshots_quality_status_check')),
    sa.CheckConstraint("quota_status IN ('NOT_APPLICABLE', 'UNKNOWN', 'OPEN', 'RESTRICTED', 'SUSPENDED')", name=op.f('ck_etf_metric_snapshots_quota_status_check')),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 1', name=op.f('ck_etf_metric_snapshots_quality_score_range')),
    sa.PrimaryKeyConstraint('etf_metric_snapshot_id', name=op.f('pk_etf_metric_snapshots'))    )
    op.create_index('ix_etf_metric_inst_asof', 'etf_metric_snapshots', ['instrument_id', sa.literal_column('as_of DESC')], unique=False)
    op.create_table('etf_nav_observations',
    sa.Column('nav_observation_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.Text(), server_default='CNY', nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('nav_observation_id', name=op.f('pk_etf_nav_observations')),
    sa.UniqueConstraint('instrument_id', 'nav_date', 'provider', name='uq_etf_nav_inst_date_provider')    )
    op.create_table('evidence_items',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('raw_object_key', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("claim_type IN ('FACT', 'INTERPRETATION', 'ESTIMATE', 'WARNING')", name=op.f('ck_evidence_items_claim_type_check')),
    sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_evidence_items_confidence_check')),
    sa.CheckConstraint("direction IN ('SUPPORT', 'CONTRADICT', 'NEUTRAL')", name=op.f('ck_evidence_items_direction_check')),
    sa.CheckConstraint("source_type IN ('OFFICIAL_FILING', 'EXCHANGE', 'NEWS', 'WEB', 'PROVIDER', 'HERMES_NOTE', 'DOCUMENT')", name=op.f('ck_evidence_items_source_type_check')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence_items'))    )
    op.create_table('financial_facts',
    sa.Column('financial_fact_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('metric_code', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Text(), nullable=True),
    sa.Column('statement_type', sa.Text(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('original_unit', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency', sa.Text(), server_default='CNY', nullable=False),
    sa.Column('unit', sa.Text(), server_default='CNY', nullable=False),
    sa.Column('is_restated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type IN ('Q1', 'H1', 'Q3', 'FY')", name=op.f('ck_financial_facts_period_type_check')),
    sa.CheckConstraint("quality_status IN ('VERIFIED', 'ACCEPTABLE', 'STALE', 'CONFLICT', 'REJECTED')", name=op.f('ck_financial_facts_quality_status_check')),
    sa.CheckConstraint("statement_type IN ('INCOME', 'BALANCE', 'CASH_FLOW', 'OTHER')", name=op.f('ck_financial_facts_statement_type_check')),
    sa.PrimaryKeyConstraint('financial_fact_id', name=op.f('pk_financial_facts')),
    sa.UniqueConstraint('instrument_id', 'metric_code', 'period_end', 'statement_type', 'published_at', 'provider', name='uq_financial_facts_inst_metric_period')    )
    op.create_index('ix_financial_facts_pit', 'financial_facts', ['instrument_id', 'metric_code', 'period_end', 'published_at'], unique=False)
    op.create_table('fx_observations',
    sa.Column('fx_observation_id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.Text(), nullable=False),
    sa.Column('quote_currency', sa.Text(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('as_of', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('fx_observation_id', name=op.f('pk_fx_observations')),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'as_of', 'provider', name='uq_fx_inst_pair_asof_provider')    )
    op.create_table('market_bar_index',
    sa.Column('bar_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('parquet_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quality_status IN ('VERIFIED', 'ACCEPTABLE', 'STALE', 'CONFLICT', 'REJECTED')", name=op.f('ck_market_bar_index_quality_status_check')),
    sa.PrimaryKeyConstraint('bar_id', name=op.f('pk_market_bar_index')),
    sa.UniqueConstraint('instrument_id', 'trade_date', 'provider', name='uq_market_bar_index_inst_date')    )
    op.create_table('portfolio_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('price_cny', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount_cny', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees_cny', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_cny', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('trade_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('reverses_transaction_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('MANUAL', 'HERMES_PAPER', 'CORPORATE_ACTION', 'REVERSAL', 'SYSTEM')", name=op.f('ck_portfolio_transactions_source_check')),
    sa.CheckConstraint("transaction_type IN ('BUY', 'SELL', 'DIVIDEND', 'FEE', 'CASH_IN', 'CASH_OUT')", name=op.f('ck_portfolio_transactions_transaction_type_check')),
    sa.CheckConstraint("transaction_type IN ('CASH_IN','CASH_OUT') OR instrument_id IS NOT NULL", name=op.f('ck_portfolio_transactions_instrument_required')),
    sa.CheckConstraint('reverses_transaction_id IS NULL OR reverses_transaction_id <> transaction_id', name=op.f('ck_portfolio_transactions_reversal')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_portfolio_transactions'))    )
    op.create_index('ix_transactions_portfolio_date', 'portfolio_transactions', ['portfolio_id', 'trade_date'], unique=False)
    op.create_index('ix_transactions_portfolio_instrument', 'portfolio_transactions', ['portfolio_id', 'instrument_id'], unique=False)
    op.create_table('research_events',
    sa.Column('research_event_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('artifact_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('research_event_id', name=op.f('pk_research_events'))    )
    op.create_table('research_notes',
    sa.Column('research_note_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('research_note_id', name=op.f('pk_research_notes'))    )
    op.create_table('thesis_red_flags',
    sa.Column('red_flag_id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('RED_LINE', 'HIGH', 'MEDIUM')", name=op.f('ck_thesis_red_flags_severity_check')),
    sa.CheckConstraint("status IN ('ARMED', 'TRIGGERED', 'RESOLVED')", name=op.f('ck_thesis_red_flags_status_check')),
    sa.PrimaryKeyConstraint('red_flag_id', name=op.f('pk_thesis_red_flags'))    )
    op.create_table('thesis_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('health_before', sa.Text(), nullable=True),
    sa.Column('health_after', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("conclusion IN ('REAFFIRM', 'REVISE', 'INVALIDATE')", name=op.f('ck_thesis_reviews_conclusion_check')),
    sa.CheckConstraint("review_type IN ('SCHEDULED_QUARTERLY', 'EVENT_DRIVEN', 'RED_FLAG', 'DRIFT_CHECK')", name=op.f('ck_thesis_reviews_review_type_check')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_thesis_reviews'))    )
    op.create_table('valuation_assumptions',
    sa.Column('valuation_assumption_id', sa.UUID(), nullable=False),
    sa.Column('valuation_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('source_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('valuation_assumption_id', name=op.f('pk_valuation_assumptions')),
    sa.UniqueConstraint('valuation_run_id', 'name', name='uq_valuation_assumptions_run_name')    )
    op.create_table('valuation_input_refs',
    sa.Column('valuation_input_ref_id', sa.UUID(), nullable=False),
    sa.Column('valuation_run_id', sa.UUID(), nullable=False),
    sa.Column('input_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('object_version', sa.Text(), nullable=True),
    sa.Column('object_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("input_type IN ('MARKET_PRICE', 'FINANCIAL_FACT', 'THESIS_REVISION', 'FX_OBSERVATION', 'PROVIDER_SNAPSHOT', 'PARQUET_DATASET', 'MANUAL')", name=op.f('ck_valuation_input_refs_input_type_check')),
    sa.PrimaryKeyConstraint('valuation_input_ref_id', name=op.f('pk_valuation_input_refs')),
    sa.UniqueConstraint('valuation_run_id', 'input_type', 'object_id', name='uq_valuation_input_refs_run_type_obj')    )
    op.create_table('evidence_links',
    sa.Column('evidence_link_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('thesis_revision_id', sa.UUID(), nullable=True),
    sa.Column('assumption_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('thesis_revision_id IS NOT NULL OR assumption_id IS NOT NULL', name=op.f('ck_evidence_links_target')),
    sa.PrimaryKeyConstraint('evidence_link_id', name=op.f('pk_evidence_links'))    )
    op.create_index('uq_evidence_links_target', 'evidence_links', ['evidence_id', sa.literal_column("COALESCE(thesis_revision_id, '00000000-0000-0000-0000-000000000000')"), sa.literal_column("COALESCE(assumption_id, '00000000-0000-0000-0000-000000000000')")], unique=True)
    op.create_table('trade_proposals',
    sa.Column('trade_proposal_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('limit_price_cny', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('thesis_revision_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('executed_transaction_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("proposal_type IN ('BUY', 'SELL')", name=op.f('ck_trade_proposals_proposal_type_check')),
    sa.CheckConstraint("status IN ('DRAFT', 'PROPOSED', 'APPROVED', 'REJECTED', 'EXECUTED')", name=op.f('ck_trade_proposals_status_check')),
    sa.PrimaryKeyConstraint('trade_proposal_id', name=op.f('pk_trade_proposals'))    )
    op.create_foreign_key(
        op.f('fk_theses_current_revision_id_thesis_revisions'), 'theses', 'thesis_revisions',
        ['current_revision_id'], ['thesis_revision_id'],
    )
    op.create_foreign_key(
        op.f('fk_theses_instrument_id_instruments'), 'theses', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_revisions_base_revision_id_thesis_revisions'), 'thesis_revisions', 'thesis_revisions',
        ['base_revision_id'], ['thesis_revision_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_revisions_provenance_id_provenance_records'), 'thesis_revisions', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_revisions_thesis_id_theses'), 'thesis_revisions', 'theses',
        ['thesis_id'], ['thesis_id'],
    )
    op.create_foreign_key(
        op.f('fk_accounts_portfolio_id_portfolios'), 'accounts', 'portfolios',
        ['portfolio_id'], ['portfolio_id'],
    )
    op.create_foreign_key(
        op.f('fk_attention_items_daily_context_id_daily_contexts'), 'attention_items', 'daily_contexts',
        ['daily_context_id'], ['daily_context_id'],
    )
    op.create_foreign_key(
        op.f('fk_attention_items_instrument_id_instruments'), 'attention_items', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_daily_briefs_daily_context_id_daily_contexts'), 'daily_briefs', 'daily_contexts',
        ['daily_context_id'], ['daily_context_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_profiles_instrument_id_instruments'), 'etf_profiles', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_profiles_underlying_index_id_instruments'), 'etf_profiles', 'instruments',
        ['underlying_index_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_portfolio_snapshots_portfolio_id_portfolios'), 'portfolio_snapshots', 'portfolios',
        ['portfolio_id'], ['portfolio_id'],
    )
    op.create_foreign_key(
        op.f('fk_position_snapshots_instrument_id_instruments'), 'position_snapshots', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_position_snapshots_portfolio_id_portfolios'), 'position_snapshots', 'portfolios',
        ['portfolio_id'], ['portfolio_id'],
    )
    op.create_foreign_key(
        op.f('fk_provenance_records_ingestion_run_id_job_runs'), 'provenance_records', 'job_runs',
        ['ingestion_run_id'], ['job_run_id'],
    )
    op.create_foreign_key(
        op.f('fk_provider_symbols_instrument_id_instruments'), 'provider_symbols', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_research_threads_workspace_id_research_workspaces'), 'research_threads', 'research_workspaces',
        ['workspace_id'], ['workspace_id'],
    )
    op.create_foreign_key(
        op.f('fk_target_allocations_instrument_id_instruments'), 'target_allocations', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_target_allocations_portfolio_id_portfolios'), 'target_allocations', 'portfolios',
        ['portfolio_id'], ['portfolio_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_assumptions_superseded_by_thesis_assumptions'), 'thesis_assumptions', 'thesis_assumptions',
        ['superseded_by'], ['assumption_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_assumptions_thesis_id_theses'), 'thesis_assumptions', 'theses',
        ['thesis_id'], ['thesis_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_assumptions_thesis_revision_id_thesis_revisions'), 'thesis_assumptions', 'thesis_revisions',
        ['thesis_revision_id'], ['thesis_revision_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_events_thesis_id_theses'), 'thesis_events', 'theses',
        ['thesis_id'], ['thesis_id'],
    )
    op.create_foreign_key(
        op.f('fk_valuation_runs_instrument_id_instruments'), 'valuation_runs', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_corporate_actions_instrument_id_instruments'), 'corporate_actions', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_corporate_actions_provenance_id_provenance_records'), 'corporate_actions', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_holding_snapshots_instrument_id_instruments'), 'etf_holding_snapshots', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_holding_snapshots_provenance_id_provenance_records'), 'etf_holding_snapshots', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_metric_snapshots_instrument_id_instruments'), 'etf_metric_snapshots', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_metric_snapshots_provenance_id_provenance_records'), 'etf_metric_snapshots', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_metric_snapshots_underlying_index_id_instruments'), 'etf_metric_snapshots', 'instruments',
        ['underlying_index_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_nav_observations_instrument_id_instruments'), 'etf_nav_observations', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_etf_nav_observations_provenance_id_provenance_records'), 'etf_nav_observations', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_evidence_items_instrument_id_instruments'), 'evidence_items', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_evidence_items_provenance_id_provenance_records'), 'evidence_items', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_financial_facts_instrument_id_instruments'), 'financial_facts', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_financial_facts_provenance_id_provenance_records'), 'financial_facts', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_fx_observations_provenance_id_provenance_records'), 'fx_observations', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_market_bar_index_instrument_id_instruments'), 'market_bar_index', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_market_bar_index_provenance_id_provenance_records'), 'market_bar_index', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_portfolio_transactions_account_id_accounts'), 'portfolio_transactions', 'accounts',
        ['account_id'], ['account_id'],
    )
    op.create_foreign_key(
        op.f('fk_portfolio_transactions_instrument_id_instruments'), 'portfolio_transactions', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_portfolio_transactions_portfolio_id_portfolios'), 'portfolio_transactions', 'portfolios',
        ['portfolio_id'], ['portfolio_id'],
    )
    op.create_foreign_key(
        op.f('fk_portfolio_transactions_provenance_id_provenance_records'), 'portfolio_transactions', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_portfolio_transactions_reverses_transaction_id_portfolio_transactions'), 'portfolio_transactions', 'portfolio_transactions',
        ['reverses_transaction_id'], ['transaction_id'],
    )
    op.create_foreign_key(
        op.f('fk_research_events_thread_id_research_threads'), 'research_events', 'research_threads',
        ['thread_id'], ['thread_id'],
    )
    op.create_foreign_key(
        op.f('fk_research_notes_instrument_id_instruments'), 'research_notes', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_research_notes_provenance_id_provenance_records'), 'research_notes', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_research_notes_thread_id_research_threads'), 'research_notes', 'research_threads',
        ['thread_id'], ['thread_id'],
    )
    op.create_foreign_key(
        op.f('fk_research_notes_workspace_id_research_workspaces'), 'research_notes', 'research_workspaces',
        ['workspace_id'], ['workspace_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_red_flags_provenance_id_provenance_records'), 'thesis_red_flags', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_red_flags_thesis_id_theses'), 'thesis_red_flags', 'theses',
        ['thesis_id'], ['thesis_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_reviews_provenance_id_provenance_records'), 'thesis_reviews', 'provenance_records',
        ['provenance_id'], ['provenance_id'],
    )
    op.create_foreign_key(
        op.f('fk_thesis_reviews_thesis_id_theses'), 'thesis_reviews', 'theses',
        ['thesis_id'], ['thesis_id'],
    )
    op.create_foreign_key(
        op.f('fk_valuation_assumptions_valuation_run_id_valuation_runs'), 'valuation_assumptions', 'valuation_runs',
        ['valuation_run_id'], ['valuation_run_id'],
    )
    op.create_foreign_key(
        op.f('fk_valuation_input_refs_valuation_run_id_valuation_runs'), 'valuation_input_refs', 'valuation_runs',
        ['valuation_run_id'], ['valuation_run_id'],
    )
    op.create_foreign_key(
        op.f('fk_evidence_links_assumption_id_thesis_assumptions'), 'evidence_links', 'thesis_assumptions',
        ['assumption_id'], ['assumption_id'],
    )
    op.create_foreign_key(
        op.f('fk_evidence_links_evidence_id_evidence_items'), 'evidence_links', 'evidence_items',
        ['evidence_id'], ['evidence_id'],
    )
    op.create_foreign_key(
        op.f('fk_evidence_links_thesis_revision_id_thesis_revisions'), 'evidence_links', 'thesis_revisions',
        ['thesis_revision_id'], ['thesis_revision_id'],
    )
    op.create_foreign_key(
        op.f('fk_trade_proposals_executed_transaction_id_portfolio_transactions'), 'trade_proposals', 'portfolio_transactions',
        ['executed_transaction_id'], ['transaction_id'],
    )
    op.create_foreign_key(
        op.f('fk_trade_proposals_instrument_id_instruments'), 'trade_proposals', 'instruments',
        ['instrument_id'], ['instrument_id'],
    )
    op.create_foreign_key(
        op.f('fk_trade_proposals_portfolio_id_portfolios'), 'trade_proposals', 'portfolios',
        ['portfolio_id'], ['portfolio_id'],
    )
    op.create_foreign_key(
        op.f('fk_trade_proposals_thesis_revision_id_thesis_revisions'), 'trade_proposals', 'thesis_revisions',
        ['thesis_revision_id'], ['thesis_revision_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f('fk_theses_current_revision_id_thesis_revisions'), 'theses', type_='foreignkey')
    op.drop_constraint(op.f('fk_theses_instrument_id_instruments'), 'theses', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_revisions_base_revision_id_thesis_revisions'), 'thesis_revisions', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_revisions_provenance_id_provenance_records'), 'thesis_revisions', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_revisions_thesis_id_theses'), 'thesis_revisions', type_='foreignkey')
    op.drop_constraint(op.f('fk_accounts_portfolio_id_portfolios'), 'accounts', type_='foreignkey')
    op.drop_constraint(op.f('fk_attention_items_daily_context_id_daily_contexts'), 'attention_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_attention_items_instrument_id_instruments'), 'attention_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_daily_briefs_daily_context_id_daily_contexts'), 'daily_briefs', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_profiles_instrument_id_instruments'), 'etf_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_profiles_underlying_index_id_instruments'), 'etf_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_portfolio_snapshots_portfolio_id_portfolios'), 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_position_snapshots_instrument_id_instruments'), 'position_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_position_snapshots_portfolio_id_portfolios'), 'position_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_provenance_records_ingestion_run_id_job_runs'), 'provenance_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_provider_symbols_instrument_id_instruments'), 'provider_symbols', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_threads_workspace_id_research_workspaces'), 'research_threads', type_='foreignkey')
    op.drop_constraint(op.f('fk_target_allocations_instrument_id_instruments'), 'target_allocations', type_='foreignkey')
    op.drop_constraint(op.f('fk_target_allocations_portfolio_id_portfolios'), 'target_allocations', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_assumptions_superseded_by_thesis_assumptions'), 'thesis_assumptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_assumptions_thesis_id_theses'), 'thesis_assumptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_assumptions_thesis_revision_id_thesis_revisions'), 'thesis_assumptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_events_thesis_id_theses'), 'thesis_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_valuation_runs_instrument_id_instruments'), 'valuation_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_corporate_actions_instrument_id_instruments'), 'corporate_actions', type_='foreignkey')
    op.drop_constraint(op.f('fk_corporate_actions_provenance_id_provenance_records'), 'corporate_actions', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_holding_snapshots_instrument_id_instruments'), 'etf_holding_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_holding_snapshots_provenance_id_provenance_records'), 'etf_holding_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_metric_snapshots_instrument_id_instruments'), 'etf_metric_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_metric_snapshots_provenance_id_provenance_records'), 'etf_metric_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_metric_snapshots_underlying_index_id_instruments'), 'etf_metric_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_nav_observations_instrument_id_instruments'), 'etf_nav_observations', type_='foreignkey')
    op.drop_constraint(op.f('fk_etf_nav_observations_provenance_id_provenance_records'), 'etf_nav_observations', type_='foreignkey')
    op.drop_constraint(op.f('fk_evidence_items_instrument_id_instruments'), 'evidence_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_evidence_items_provenance_id_provenance_records'), 'evidence_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_financial_facts_instrument_id_instruments'), 'financial_facts', type_='foreignkey')
    op.drop_constraint(op.f('fk_financial_facts_provenance_id_provenance_records'), 'financial_facts', type_='foreignkey')
    op.drop_constraint(op.f('fk_fx_observations_provenance_id_provenance_records'), 'fx_observations', type_='foreignkey')
    op.drop_constraint(op.f('fk_market_bar_index_instrument_id_instruments'), 'market_bar_index', type_='foreignkey')
    op.drop_constraint(op.f('fk_market_bar_index_provenance_id_provenance_records'), 'market_bar_index', type_='foreignkey')
    op.drop_constraint(op.f('fk_portfolio_transactions_account_id_accounts'), 'portfolio_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_portfolio_transactions_instrument_id_instruments'), 'portfolio_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_portfolio_transactions_portfolio_id_portfolios'), 'portfolio_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_portfolio_transactions_provenance_id_provenance_records'), 'portfolio_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_portfolio_transactions_reverses_transaction_id_portfolio_transactions'), 'portfolio_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_events_thread_id_research_threads'), 'research_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_notes_instrument_id_instruments'), 'research_notes', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_notes_provenance_id_provenance_records'), 'research_notes', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_notes_thread_id_research_threads'), 'research_notes', type_='foreignkey')
    op.drop_constraint(op.f('fk_research_notes_workspace_id_research_workspaces'), 'research_notes', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_red_flags_provenance_id_provenance_records'), 'thesis_red_flags', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_red_flags_thesis_id_theses'), 'thesis_red_flags', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_reviews_provenance_id_provenance_records'), 'thesis_reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_thesis_reviews_thesis_id_theses'), 'thesis_reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_valuation_assumptions_valuation_run_id_valuation_runs'), 'valuation_assumptions', type_='foreignkey')
    op.drop_constraint(op.f('fk_valuation_input_refs_valuation_run_id_valuation_runs'), 'valuation_input_refs', type_='foreignkey')
    op.drop_constraint(op.f('fk_evidence_links_assumption_id_thesis_assumptions'), 'evidence_links', type_='foreignkey')
    op.drop_constraint(op.f('fk_evidence_links_evidence_id_evidence_items'), 'evidence_links', type_='foreignkey')
    op.drop_constraint(op.f('fk_evidence_links_thesis_revision_id_thesis_revisions'), 'evidence_links', type_='foreignkey')
    op.drop_constraint(op.f('fk_trade_proposals_executed_transaction_id_portfolio_transactions'), 'trade_proposals', type_='foreignkey')
    op.drop_constraint(op.f('fk_trade_proposals_instrument_id_instruments'), 'trade_proposals', type_='foreignkey')
    op.drop_constraint(op.f('fk_trade_proposals_portfolio_id_portfolios'), 'trade_proposals', type_='foreignkey')
    op.drop_constraint(op.f('fk_trade_proposals_thesis_revision_id_thesis_revisions'), 'trade_proposals', type_='foreignkey')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_proposals')
    op.drop_index('uq_evidence_links_target', table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_table('valuation_input_refs')
    op.drop_table('valuation_assumptions')
    op.drop_table('thesis_reviews')
    op.drop_table('thesis_red_flags')
    op.drop_table('research_notes')
    op.drop_table('research_events')
    op.drop_index('ix_transactions_portfolio_instrument', table_name='portfolio_transactions')
    op.drop_index('ix_transactions_portfolio_date', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_table('market_bar_index')
    op.drop_table('fx_observations')
    op.drop_index('ix_financial_facts_pit', table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_table('evidence_items')
    op.drop_table('etf_nav_observations')
    op.drop_index('ix_etf_metric_inst_asof', table_name='etf_metric_snapshots')
    op.drop_table('etf_metric_snapshots')
    op.drop_table('etf_holding_snapshots')
    op.drop_index('ix_corporate_actions_inst_exdate', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index('ix_valuation_runs_inst_asof', table_name='valuation_runs')
    op.drop_table('valuation_runs')
    op.drop_index('ix_thesis_events_thesis', table_name='thesis_events')
    op.drop_table('thesis_events')
    op.drop_table('thesis_assumptions')
    op.drop_table('target_allocations')
    op.drop_table('research_threads')
    op.drop_index('ix_provider_symbols_lookup', table_name='provider_symbols', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index('ix_provider_symbols_instrument', table_name='provider_symbols')
    op.drop_table('provider_symbols')
    op.drop_index('ix_provenance_provider_record', table_name='provenance_records')
    op.drop_index('ix_provenance_asof_quality', table_name='provenance_records')
    op.drop_table('provenance_records')
    op.drop_index('ix_position_snapshots_pf_date', table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('etf_profiles')
    op.drop_table('daily_briefs')
    op.drop_table('attention_items')
    op.drop_table('accounts')
    op.drop_table('trading_calendar')
    op.drop_index('ix_thesis_revisions_thesis', table_name='thesis_revisions')
    op.drop_table('thesis_revisions')
    op.drop_table('theses')
    op.drop_table('research_workspaces')
    op.drop_table('portfolios')
    op.drop_table('outbox_events')
    op.drop_index('ix_job_runs_name_created', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('instruments')
    op.drop_table('daily_contexts')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
